In [1]:
import sys, os
from pymongo import MongoClient

import pandas as pd

import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics

from plotly.offline import init_notebook_mode, iplot
from plotly.graph_objs import *

# https://stackoverflow.com/questions/41323423/plotly-inside-jupyter-notebook-python
init_notebook_mode(connected=True) # initiate notebook for offline plot

from dotenv import load_dotenv

In [2]:
load_dotenv("../.env")

True

In [3]:
sys.path.append("../src/")
import common # ../src/common.py

uri = f"mongodb://root:{os.environ['MONGODB_ROOT_PASSWORD']}@{os.environ['MONGODB_IP']}:{os.environ['MONGODB_PORT']}/"

client = MongoClient(uri)
db = client['steam']

In [4]:
dates_df = pd.DataFrame(list(db['apps'].aggregate
([
        {'$match': {"$or":[
            {'type': "game"},
            {'type': "dlc"}
        ]}},
    {"$project": {"_id":False, "appid":1, "release_date":"$release_date.date"}}
]))).dropna()

dates_df

          appid         release_date
0            10  2000-11-01 00:00:00
1            20  1999-04-01 00:00:00
2            30  2003-05-01 00:00:00
3            40  2001-06-01 00:00:00
4            50  1999-11-01 00:00:00
...         ...                  ...
234725  4165060  2026-03-19 00:00:00
234726  4165960      To be announced
234727  4166250                 2027
234728  4166710  2026-03-06 00:00:00
234729  4166750  2025-12-16 00:00:00

[234730 rows x 2 columns]

In [5]:
dates_df.release_date = pd.to_datetime(dates_df.release_date, format='%Y-%m-%d', errors='coerce')

dates_df = dates_df[pd.notnull(dates_df['release_date'])]

dates_df

          appid release_date
0            10   2000-11-01
1            20   1999-04-01
2            30   2003-05-01
3            40   2001-06-01
4            50   1999-11-01
...         ...          ...
234723  4164620   2026-02-25
234724  4164640   2025-11-25
234725  4165060   2026-03-19
234728  4166710   2026-03-06
234729  4166750   2025-12-16

[198024 rows x 2 columns]

In [6]:
price_hist_df = pd.DataFrame(list(db['pricehistory'].find({"discount_percent": {"$ne":0}}, {"appid":1,"discount_percent":1,"date":1,"_id":False})))

price_hist_df

           appid                    date  discount_percent
0         270270 2018-09-04 03:05:16.176                60
1         371200 2018-09-04 03:05:20.772                67
2         283940 2018-09-04 03:05:20.774                60
3         717370 2018-09-04 03:05:25.393                51
4         933890 2018-09-04 03:05:32.206                40
...          ...                     ...               ...
8342574  3678810 2026-05-22 13:27:39.978                80
8342575  3690750 2026-05-22 13:27:41.947                20
8342576  3730720 2026-05-22 13:27:43.903                50
8342577  3737600 2026-05-22 13:27:45.848                50
8342578  3987810 2026-05-22 13:27:49.815                35

[8342579 rows x 3 columns]

In [7]:
filtered_df = price_hist_df.query('discount_percent>=50')
# sanity check:
#filtered_df.query("appid==552520").sort_values(by='date', ascending=True)

# this will find the earliest occurence of a discount per appid
filtered_df = filtered_df.loc[filtered_df.groupby(filtered_df.appid, as_index=False).date.idxmin()]

# https://isthereanydeal.com/game/farcryv/history/?shop%5B%5D=steam&generate=Select+Stores
# appid: 552520 is Far Cry 5
# this test should return one entry, the earliest timepoint at which the game met or
# exceeded that discount percentage
#filtered_df.query("appid==552520")

filtered_df

ValueError: Cannot index with multidimensional key

In [ ]:
model_df = pd.merge(dates_df,
                 filtered_df,
                 on='appid', 
                 how='left').dropna()
# drop NAs removes the cases where we have no price history information

model_df

In [ ]:
model_df['length_in_days_since_release'] = (model_df['date'] - model_df['release_date']).dt.days

model_df = model_df.sort_values(by='length_in_days_since_release', ascending=True)

model_df

In [ ]:
grped_df = model_df.groupby(['length_in_days_since_release']).size().reset_index(name='counts')
grped_df

In [ ]:
# https://plot.ly/python/bar-charts/

data = [Bar(
        x=grped_df['length_in_days_since_release'],
        y=grped_df['counts']
    )]

layout = Layout(
        title='Amount in days since the release until each game hits discount percentage mark',
        xaxis=dict(
            title='Amount in days since release'
        ),
        yaxis=dict(
            title='Count'
        )
    )

fig = Figure(data=data, layout=layout)

iplot(fig)

In [ ]:
opencriticavg_df = pd.DataFrame(list(
    db['opencritic'].aggregate([
        {'$match': {"$and":[
            {'steamId': {'$exists':True}},
            {'steamId': {'$ne':None}},
            {'steamId': {'$ne': ''}},
            {'steamId': {'$ne':'null'}},
            {'steamId': {'$ne':'NaN'}}
        ]}},
        {"$project" : {"appid":"$steamId", "avgscore":{"$avg": "$Reviews.score"}}},
        {'$match':{'avgscore': {'$ne': None}}},
        {"$project": {"_id": 0}}
    ])
)).sort_values(by='appid', ascending=False)

opencriticavg_df = opencriticavg_df.astype({"appid": int})

opencriticavg_df

In [ ]:
model_df = pd.merge(model_df,
                 opencriticavg_df,
                 on='appid', 
                 how='left').dropna()

model_df

In [ ]:
recommendations_df = pd.DataFrame(list(
    db['apps'].aggregate([
        {"$project": {"_id": False, "appid": 1, "steam_recommendations": "$recommendations.total"}}
    ])
)).fillna(0)

recommendations_df

In [ ]:
model_df = pd.merge(model_df,
                 recommendations_df,
                 on='appid', 
                 how='left').dropna()

model_df

In [ ]:
x = model_df.iloc[:, 5:6].values # predictive feature engineering inputs
y = model_df.iloc[:, 4].values # what we're trying to predict

X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [ ]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
regressor = RandomForestRegressor(n_estimators=600, random_state=0)
regressor.fit(X_train, Y_train)
Y_pred = regressor.predict(X_test)

In [ ]:
# https://medium.com/acing-ai/how-to-evaluate-regression-models-d183b4f5853d
print('Mean Absolute Error:', metrics.mean_absolute_error(Y_test, Y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(Y_test, Y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(Y_test, Y_pred)))